export const info = {
    name: 'tesseract',
    icon: 'logo/tesseract.png',
};

export enum Language {
    auto = 'eng',
    zh_cn = 'chi_sim',
    zh_tw = 'chi_tra',
    en = 'eng',
    yue = 'chi_sim',
    ja = 'jpn',
    ko = 'kor',
    fr = 'fra',
    es = 'spa',
    ru = 'rus',
    de = 'deu',
    it = 'ita',
    tr = 'tur',
    pt_pt = 'por',
    pt_br = 'por',
    vi = 'vie',
    id = 'ind',
    th = 'tha',
    ms = 'msa',
    ar = 'ara',
    hi = 'hin',
    uk = 'ukr',
    he = 'heb',
}
