export const info = {
    name: 'bing',
    icon: 'logo/bing.svg',
};
// https://learn.microsoft.com/en-us/azure/ai-services/translator/language-support
export enum Language {
    auto = '',
    zh_cn = 'zh-Hans',
    zh_tw = 'zh-Hant',
    yue = 'yue',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt-pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_cy = 'mn-Cyrl',
    mn_mo = 'mn-Mong',
    km = 'km',
    nb_no = 'nb',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
