export const info = {
    name: 'lingva',
    icon: 'logo/lingva.svg',
};

// https://cloud.google.com/translate/docs/languages?hl=zh-cn
export enum Language {
    auto = 'auto',
    zh_cn = 'zh',
    zh_tw = 'zh_HANT',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_cy = 'mn',
    mn_mo = 'mn',
    km = 'km',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
