name: Bug 反馈
description: 反馈使用过程中遇到的问题
title: "[Bug]: "
labels: ["bug", "待验证"]
assignees:
  - Pylogmon
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢反馈，pot因您的反馈变得更好！
  - type: textarea
    id: detials
    attributes:
      label: 问题描述
      description: 简单描述遇到的问题
    validations:
      required: true
  - type: textarea
    id: detials
    attributes:
      label: 如何复现
      description: 详细描述复现问题的步骤
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 操作系统
      description: 你使用的操作系统
      options:
        - Windows (Default)
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: window
    attributes:
      label: 窗口系统（Linux Only）
      options:
        - X11
        - Wayland
  - type: textarea
    id: ext
    attributes:
      label: 补充信息
      description: 其他需要补充的信息
      render: shell
