export const info = {
    name: 'baidu_field',
    icon: 'logo/baidu.svg',
};
// https://fanyi-api.baidu.com/product/113
export enum Language {
    auto = 'auto',
    zh_cn = 'zh',
    zh_tw = 'cht',
    yue = 'yue',
    en = 'en',
    ja = 'jp',
    ko = 'kor',
    fr = 'fra',
    es = 'spa',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pot',
    vi = 'vie',
    id = 'id',
    th = 'th',
    ms = 'may',
    ar = 'ar',
    hi = 'hi',
    km = 'hkm',
    nb_no = 'nob',
    nn_no = 'nno',
    fa = 'per',
    sv = 'swe',
    pl = 'pl',
    nl = 'nl',
    uk = 'ukr',
    he = 'heb',
}
