import * as _deepl from './deepl';
import * as _bing from './bing';
import * as _yandex from './yandex';
import * as _openai from './openai';
import * as _openai_summary from './openai_summary';
import * as _openai_polish from './openai_polish';
import * as _openai_custom from './openai_custom';
import * as _google from './google';
import * as _transmart from './transmart';
import * as _alibaba from './alibaba';
import * as _baidu from './baidu';
import * as _baidu_field from './baidu_field';
import * as _tencent from './tencent';
import * as _volcengine from './volcengine';
import * as _niutrans from './niutrans';
import * as _youdao from './youdao';
import * as _bing_dict from './bing_dict';
import * as _cambridge_dict from './cambridge_dict';
import * as _caiyun from './caiyun';
import * as _chatglm from './chatglm';

export const deepl = _deepl;
export const bing = _bing;
export const yandex = _yandex;
export const openai = _openai;
export const openai_summary = _openai_summary;
export const openai_polish = _openai_polish;
export const openai_custom = _openai_custom;
export const google = _google;
export const transmart = _transmart;
export const alibaba = _alibaba;
export const baidu = _baidu;
export const baidu_field = _baidu_field;
export const tencent = _tencent;
export const volcengine = _volcengine;
export const niutrans = _niutrans;
export const youdao = _youdao;
export const bing_dict = _bing_dict;
export const cambridge_dict = _cambridge_dict;
export const caiyun = _caiyun;
export const chatglm = _chatglm;
