import * as _tesseract from './tesseract';
import * as _baidu from './baidu';
import * as _baidu_accurate from './baidu_accurate';
import * as _tencent from './tencent';
import * as _tencent_accurate from './tencent_accurate';
import * as _tencent_img from './tencent_img';
import * as _ocrspace1 from './ocrspace1';
import * as _ocrspace2 from './ocrspace2';
import * as _ocrspace3 from './ocrspace3';
import * as _volcengine from './volcengine';
import * as _volcengine_multi_lang from './volcengine_multi_lang';
import * as _simplelatex from './simplelatex';
import * as _iflytek_latex from './iflytek_latex';
import * as _iflytek from './iflytek';
import * as _iflytek_intsig from './iflytek_intsig';
import * as _qrcode from './qrcode';

export const tesseract = _tesseract;
export const baidu = _baidu;
export const baidu_accurate = _baidu_accurate;
export const tencent = _tencent;
export const tencent_accurate = _tencent_accurate;
export const tencent_img = _tencent_img;
export const ocrspace1 = _ocrspace1;
export const ocrspace2 = _ocrspace2;
export const ocrspace3 = _ocrspace3;
export const volcengine = _volcengine;
export const volcengine_multi_lang = _volcengine_multi_lang;
export const simplelatex = _simplelatex;
export const iflytek_latex = _iflytek_latex;
export const iflytek = _iflytek;
export const iflytek_intsig = _iflytek_intsig;
export const qrcode = _qrcode;