// ISO-639-1 + Country Code (Option)
// https://zh.wikipedia.org/wiki/ISO_639-1%E4%BB%A3%E7%A0%81%E8%A1%A8
export const languageList = [
    'zh_cn',
    'zh_tw',
    'mn_mo',
    'en',
    'ja',
    'ko',
    'fr',
    'es',
    'ru',
    'de',
    'it',
    'tr',
    'pt_pt',
    'pt_br',
    'vi',
    'id',
    'th',
    'ms',
    'ar',
    'hi',
    'km',
    'mn_cy',
    'nb_no',
    'nn_no',
    'fa',
    'sv',
    'pl',
    'nl',
];

// https://flagicons.lipis.dev/
export enum LanguageFlag {
    zh_cn = 'cn',
    zh_tw = 'cn',
    mn_mo = 'cn',
    en = 'gb',
    ja = 'jp',
    ko = 'kr',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'br',
    vi = 'vn',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ae',
    hi = 'in',
    km = 'kh',
    mn_cy = 'mn',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'ir',
    sv = 'se',
    pl = 'pl',
    nl = 'nl',
}
