export const info = {
    name: 'youdao',
    icon: 'logo/youdao.svg',
};

export enum Language {
    auto = 'auto',
    zh_cn = 'zh-CHS',
    zh_tw = 'zh-CHT',
    yue = 'yue',
    en = 'en',
    ja = 'jp',
    ko = 'kor',
    fr = 'fra',
    es = 'spa',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt = 'pt',
    pt_br = 'pt',
    vi = 'vie',
    id = 'id',
    th = 'th',
    ms = 'may',
    ar = 'ar',
    hi = 'hi',
    mn_mo = 'mn',
    km = 'km',
}
