export const info = {
    name: 'youdao',
    icon: 'logo/youdao.svg',
};
// https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html
export enum Language {
    auto = 'auto',
    zh_cn = 'zh-CHS',
    zh_tw = 'zh-CHT',
    yue = 'yue',
    en = 'en',
    ja = 'jp',
    ko = 'kor',
    fr = 'fra',
    es = 'spa',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vie',
    id = 'id',
    th = 'th',
    ms = 'may',
    ar = 'ar',
    hi = 'hi',
    mn_mo = 'mn',
    km = 'km',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
