export const info = {
    name: 'chatglm',
    icon: 'logo/chatglm.png',
};

export enum Language {
    auto = 'Auto',
    zh_cn = 'Simplified Chinese',
    zh_tw = 'Traditional Chinese',
    yue = 'Cantonese',
    ja = 'Japanese',
    en = 'English',
    ko = 'Korean',
    fr = 'French',
    es = 'Spanish',
    ru = 'Russian',
    de = 'German',
    it = 'Italian',
    tr = 'Turkish',
    pt_pt = 'Portuguese',
    pt_br = 'Brazilian Portuguese',
    vi = 'Vietnamese',
    id = 'Indonesian',
    th = 'Thai',
    ms = 'Malay',
    ar = 'Arabic',
    hi = 'Hindi',
    mn_mo = 'Mongolian',
    mn_cy = 'Mongolian(Cyrillic)',
    km = 'Khmer',
    nb_no = 'Norwegian Bokmål',
    nn_no = 'Norwegian Nynorsk',
    fa = 'Persian',
    sv = 'Swedish',
    pl = 'Polish',
    nl = 'Dutch',
    uk = 'Ukrainian',
    he = 'Hebrew',
}
