export const info = {
    name: 'niutrans',
    icon: 'logo/niutrans.svg',
};
// https://niutrans.com/documents/contents/trans_text#languageList
export enum Language {
    auto = 'auto',
    zh_cn = 'zh',
    zh_tw = 'cht',
    yue = 'yue',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_cy = 'mn',
    mn_mo = 'mo',
    km = 'km',
    nb_no = 'nb',
    nn_no = 'nn',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
