export const info = {
    name: 'alibaba',
    icon: 'logo/alibaba.svg',
};
// https://help.aliyun.com/document_detail/215387.html?spm=a2c4g.158269.0.0.ddfc4f62vEpa38
export enum Language {
    auto = 'auto',
    zh_cn = 'zh',
    zh_tw = 'zh-tw',
    yue = 'yue',
    ja = 'ja',
    en = 'en',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_mo = 'mn',
    km = 'km',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    he = 'he',
}
